version: '3'
services:
  db:
    image: mysql:5
    # volumes:
    #   - ./data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: qbf_demo
